'use client';

import React from 'react';
import { ReportProps, ReportSection } from '../../../types/generative';
import classNames from 'classnames';
import { Printer } from 'lucide-react';

export const Report: React.FC<ReportProps> = ({
    title,
    summary,
    sections,
    footer,
    generatedDate,
    author,
    printable = true,
}) => {
    const handlePrint = () => {
        window.print();
    };

    const renderMetrics = (metrics: ReportSection['metrics']) => {
        if (!metrics || metrics.length === 0) return null;

        return (
            <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-4 my-6">
                {metrics.map((metric, idx) => {
                    const statusColors = {
                        positive: 'text-green-600 bg-green-50 border-green-100',
                        negative: 'text-red-600 bg-red-50 border-red-100',
                        neutral: 'text-gray-600 bg-gray-50 border-gray-100',
                    };
                    const colorClass = statusColors[metric.status || 'neutral'];

                    return (
                        <div key={idx} className={classNames('p-4 rounded-lg border', colorClass)}>
                            <div className="text-sm font-medium opacity-80">{metric.label}</div>
                            <div className="text-2xl font-bold mt-1">
                                {metric.value}
                                {metric.unit && <span className="text-sm ml-1 font-normal opacity-70">{metric.unit}</span>}
                            </div>
                        </div>
                    );
                })}
            </div>
        );
    };

    return (
        <div className="bg-white rounded-lg shadow-sm border border-gray-200 overflow-hidden print:shadow-none print:border-0 p-8 max-w-4xl mx-auto">
            {/* Header */}
            <div className="border-b border-gray-200 pb-6 mb-6 flex justify-between items-start">
                <div>
                    <h1 className="text-3xl font-bold text-gray-900">{title}</h1>
                    <div className="mt-2 text-sm text-gray-500 space-y-1">
                        {author && <p>Prepared by: {author}</p>}
                        {generatedDate && <p>Date: {generatedDate}</p>}
                    </div>
                </div>
                {printable && (
                    <button
                        onClick={handlePrint}
                        className="print:hidden p-2 text-gray-500 hover:text-gray-700 hover:bg-gray-100 rounded-full transition-colors"
                        title="Print Report"
                    >
                        <Printer size={20} />
                    </button>
                )}
            </div>

            {/* Summary */}
            {summary && (
                <div className="bg-blue-50 border-l-4 border-blue-500 p-4 mb-8">
                    <h2 className="text-sm font-bold text-blue-900 uppercase tracking-wide mb-1">Executive Summary</h2>
                    <p className="text-blue-800 leading-relaxed">{summary}</p>
                </div>
            )}

            {/* Sections */}
            <div className="space-y-10">
                {sections.map((section) => (
                    <section key={section.id} className="break-inside-avoid">
                        <h2 className="text-xl font-bold text-gray-800 border-b border-gray-100 pb-2 mb-4">
                            {section.title}
                        </h2>

                        {section.content && (
                            <div className="prose prose-gray max-w-none text-gray-600 mb-4 whitespace-pre-line">
                                {section.content}
                            </div>
                        )}

                        {renderMetrics(section.metrics)}

                        {section.subsections?.map((sub, idx) => (
                            <div key={idx} className="mt-6 ml-4">
                                <h3 className="text-lg font-semibold text-gray-800 mb-2">{sub.title}</h3>
                                <div className="prose prose-sm prose-gray max-w-none text-gray-600 whitespace-pre-line">
                                    {sub.content}
                                </div>
                            </div>
                        ))}
                    </section>
                ))}
            </div>

            {/* Footer */}
            {(footer || generatedDate) && (
                <div className="mt-12 pt-6 border-t border-gray-200 text-center text-xs text-gray-400">
                    {footer && <p className="mb-1">{footer}</p>}
                    <p>Generated by All-in-One Chat AI</p>
                </div>
            )}
        </div>
    );
};
