/**
 * Component Schemas - Zod validation schemas for all component types
 * Used to validate component props generated by LLM
 */

import { z } from 'zod';
import {
  ChartProps,
  TableProps,
  CardProps,
  FormProps,
  ListProps,
  SlidesProps,
  ReportProps,
} from './core.types';

/**
 * Chart Component Schema
 */
export const ChartPropsSchema = z.object({
  chartType: z.enum(['line', 'bar', 'area', 'pie', 'scatter', 'radar', 'combo']),
  data: z.array(z.record(z.unknown())),
  xAxis: z.optional(
    z.object({
      key: z.string(),
      label: z.optional(z.string()),
      type: z.optional(z.string()),
    })
  ),
  yAxis: z.optional(
    z.object({
      key: z.string(),
      label: z.optional(z.string()),
      type: z.optional(z.string()),
    })
  ),
  dataKey: z.optional(z.string()),
  title: z.optional(z.string()),
  colors: z.optional(z.array(z.string())),
  showLegend: z.optional(z.boolean()),
  showTooltip: z.optional(z.boolean()),
  height: z.optional(z.number()),
  responsive: z.optional(z.boolean()),
}) as z.ZodType<ChartProps>;

/**
 * Table Component Schema
 */
export const TablePropsSchema = z.object({
  columns: z.array(
    z.object({
      key: z.string(),
      label: z.string(),
      width: z.optional(z.union([z.number(), z.string()])),
      sortable: z.optional(z.boolean()),
      type: z.optional(z.enum(['text', 'number', 'date', 'status'])),
    })
  ),
  data: z.array(z.record(z.unknown())),
  title: z.optional(z.string()),
  striped: z.optional(z.boolean()),
  hover: z.optional(z.boolean()),
  maxHeight: z.optional(z.number()),
  pagination: z.optional(
    z.object({
      enabled: z.boolean(),
      pageSize: z.optional(z.number()),
    })
  ),
}) as z.ZodType<TableProps>;

/**
 * Card Component Schema
 */
export const CardPropsSchema = z.object({
  title: z.optional(z.string()),
  content: z.optional(z.string()).default(''),  // LLM may not provide content, default to empty
  footer: z.optional(z.string()),
  variant: z.optional(z.string()),  // Relaxed: accept any string variant from LLM
  icon: z.optional(z.string()),
  image: z.optional(z.string()),
  actions: z.optional(
    z.array(
      z.object({
        label: z.string(),
        onClick: z.optional(z.string()),
      })
    )
  ),
  clickable: z.optional(z.boolean()),
}) as z.ZodType<CardProps>;

/**
 * Form Component Schema
 */
export const FormPropsSchema = z.object({
  title: z.optional(z.string()),
  fields: z.array(
    z.object({
      name: z.string(),
      label: z.string(),
      type: z.enum([
        'text',
        'email',
        'password',
        'number',
        'date',
        'checkbox',
        'radio',
        'select',
        'textarea',
      ]),
      placeholder: z.optional(z.string()),
      required: z.optional(z.boolean()),
      options: z.optional(
        z.array(
          z.object({
            label: z.string(),
            value: z.string(),
          })
        )
      ),
      rows: z.optional(z.number()),
      defaultValue: z.optional(z.string()),
      validation: z.optional(
        z.object({
          pattern: z.optional(z.string()),
          minLength: z.optional(z.number()),
          maxLength: z.optional(z.number()),
        })
      ),
    })
  ),
  submitLabel: z.optional(z.string()),
  cancelLabel: z.optional(z.string()),
  layout: z.optional(z.enum(['vertical', 'horizontal'])),
  onSubmit: z.optional(
    z.object({
      action: z.string(),
      endpoint: z.optional(z.string()),
    })
  ),
}) as z.ZodType<FormProps>;

/**
 * List Component Schema
 */
export const ListPropsSchema = z.object({
  items: z.array(
    z.object({
      id: z.string(),
      title: z.string(),
      description: z.optional(z.string()),
      icon: z.optional(z.string()),
      badge: z.optional(z.string()),
      badgeColor: z.optional(z.string()),
      avatar: z.optional(z.string()),
      selected: z.optional(z.boolean()),
      disabled: z.optional(z.boolean()),
      metadata: z.optional(z.record(z.unknown())),
    })
  ),
  title: z.optional(z.string()),
  ordered: z.optional(z.boolean()),
  variant: z.optional(z.enum(['simple', 'card', 'interactive'])),
  selectable: z.optional(z.boolean()),
  searchable: z.optional(z.boolean()),
  maxHeight: z.optional(z.number()),
}) as z.ZodType<ListProps>;

/**
 * Slides Component Schema
 */
export const SlidesPropsSchema = z.object({
  slides: z.array(
    z.object({
      id: z.string(),
      title: z.string(),
      content: z.string(),
      image: z.optional(z.string()),
      backgroundColor: z.optional(z.string()),
      textColor: z.optional(z.string()),
    })
  ),
  title: z.optional(z.string()),
  autoPlay: z.optional(z.boolean()),
  autoPlayInterval: z.optional(z.number()),
  showNavigationDots: z.optional(z.boolean()),
  showNavigationArrows: z.optional(z.boolean()),
  height: z.optional(z.number()),
}) as z.ZodType<SlidesProps>;

/**
 * Report Component Schema
 */
export const ReportPropsSchema = z.object({
  title: z.string(),
  summary: z.optional(z.string()),
  sections: z.array(
    z.object({
      id: z.string(),
      title: z.string(),
      content: z.optional(z.string()),
      subsections: z.optional(
        z.array(
          z.object({
            title: z.string(),
            content: z.string(),
          })
        )
      ),
      metrics: z.optional(
        z.array(
          z.object({
            label: z.string(),
            value: z.union([z.string(), z.number()]),
            unit: z.optional(z.string()),
            status: z.optional(z.enum(['positive', 'neutral', 'negative'])),
          })
        )
      ),
    })
  ),
  footer: z.optional(z.string()),
  generatedDate: z.optional(z.string()),
  author: z.optional(z.string()),
  printable: z.optional(z.boolean()),
}) as z.ZodType<ReportProps>;

/**
 * Component Schema Map - Mapping from component type to its Zod schema
 */
export const ComponentSchemaMap = {
  chart: ChartPropsSchema,
  table: TablePropsSchema,
  card: CardPropsSchema,
  form: FormPropsSchema,
  list: ListPropsSchema,
  slides: SlidesPropsSchema,
  report: ReportPropsSchema,
} as const;

/**
 * Validate component props by type
 * Returns validated props or throws ZodError
 */
export function validateComponentProps(
  type: keyof typeof ComponentSchemaMap,
  props: unknown
) {
  const schema = ComponentSchemaMap[type];
  return schema.parse(props);
}

/**
 * Safe validation - returns result with error info if validation fails
 */
export function validateComponentPropsSafe(
  type: keyof typeof ComponentSchemaMap,
  props: unknown
) {
  const schema = ComponentSchemaMap[type];
  return schema.safeParse(props);
}

/**
 * Get JSON Schema for a component type (useful for LLM prompts)
 */
export const ComponentJsonSchemas = {
  chart: {
    type: 'object',
    required: ['chartType', 'data'],
    properties: {
      chartType: {
        type: 'string',
        enum: ['line', 'bar', 'area', 'pie', 'scatter', 'radar', 'combo'],
        description: 'Type of chart to display',
      },
      data: {
        type: 'array',
        description: 'Array of data objects',
        items: { type: 'object' },
      },
      xAxis: {
        type: 'object',
        properties: {
          key: { type: 'string', description: 'Data key for x-axis' },
          label: { type: 'string', description: 'X-axis label' },
        },
      },
      yAxis: {
        type: 'object',
        properties: {
          key: { type: 'string', description: 'Data key for y-axis' },
          label: { type: 'string', description: 'Y-axis label' },
        },
      },
      title: { type: 'string' },
      showLegend: { type: 'boolean' },
      showTooltip: { type: 'boolean' },
    },
  },
  table: {
    type: 'object',
    required: ['columns', 'data'],
    properties: {
      columns: {
        type: 'array',
        items: {
          type: 'object',
          required: ['key', 'label'],
          properties: {
            key: { type: 'string' },
            label: { type: 'string' },
            sortable: { type: 'boolean' },
            type: { type: 'string', enum: ['text', 'number', 'date', 'status'] },
          },
        },
      },
      data: {
        type: 'array',
        description: 'Array of row objects. Keys must match column.key',
        items: { type: 'object' },
      },
      title: { type: 'string' },
      striped: { type: 'boolean' },
      hover: { type: 'boolean' },
    },
  },
  card: {
    type: 'object',
    required: ['content'],
    properties: {
      title: { type: 'string' },
      content: { type: 'string', description: 'Main card content' },
      footer: { type: 'string' },
      variant: { type: 'string', enum: ['default', 'success', 'warning', 'error', 'info'] },
      icon: { type: 'string', description: 'Icon name (lucide-react)' },
      image: { type: 'string', description: 'Image URL' },
    },
  },
  form: {
    type: 'object',
    required: ['fields'],
    properties: {
      title: { type: 'string' },
      fields: {
        type: 'array',
        items: {
          type: 'object',
          required: ['name', 'label', 'type'],
          properties: {
            name: { type: 'string' },
            label: { type: 'string' },
            type: {
              type: 'string',
              enum: ['text', 'email', 'password', 'number', 'date', 'checkbox', 'radio', 'select', 'textarea'],
            },
            placeholder: { type: 'string' },
            required: { type: 'boolean' },
            options: {
              type: 'array',
              description: 'For select/radio types',
              items: {
                type: 'object',
                properties: {
                  label: { type: 'string' },
                  value: { type: 'string' },
                },
              },
            },
          },
        },
      },
      submitLabel: { type: 'string' },
    },
  },
  list: {
    type: 'object',
    required: ['items'],
    properties: {
      items: {
        type: 'array',
        items: {
          type: 'object',
          required: ['id', 'title'],
          properties: {
            id: { type: 'string' },
            title: { type: 'string' },
            description: { type: 'string' },
            icon: { type: 'string' },
            badge: { type: 'string' },
            avatar: { type: 'string' },
          },
        },
      },
      title: { type: 'string' },
      variant: { type: 'string', enum: ['simple', 'card', 'interactive'] },
      selectable: { type: 'boolean' },
    },
  },
  slides: {
    type: 'object',
    required: ['slides'],
    properties: {
      slides: {
        type: 'array',
        items: {
          type: 'object',
          required: ['id', 'title', 'content'],
          properties: {
            id: { type: 'string' },
            title: { type: 'string' },
            content: { type: 'string' },
            image: { type: 'string', description: 'Image URL' },
          },
        },
      },
      autoPlay: { type: 'boolean' },
      autoPlayInterval: { type: 'number', description: 'Milliseconds' },
    },
  },
  report: {
    type: 'object',
    required: ['title', 'sections'],
    properties: {
      title: { type: 'string' },
      summary: { type: 'string' },
      sections: {
        type: 'array',
        items: {
          type: 'object',
          required: ['id', 'title'],
          properties: {
            id: { type: 'string' },
            title: { type: 'string' },
            content: { type: 'string' },
            metrics: {
              type: 'array',
              items: {
                type: 'object',
                properties: {
                  label: { type: 'string' },
                  value: { oneOf: [{ type: 'string' }, { type: 'number' }] },
                  status: { type: 'string', enum: ['positive', 'neutral', 'negative'] },
                },
              },
            },
          },
        },
      },
    },
  },
};
